### PR TITLE
Include simulation/orogen/vortex

### PR DESCRIPTION
**Pull request by gonzalopd96**
Include simulation/orogen/vortex for ExoTeR Vortex Studio simulations; remove drivers/udp since it should be located in rover-package-set.

### CODE REVIEW

**Comment by wieset** [comment]
Hey! As far as I can see, drivers/udp is only used for the exoter simulations, so I think this should stay in this package set. What was your reasoning for wanting to move it?

**Comment by gonzalopd96** [comment]
Hey Tim! Well, I think drivers/udp is a very generic feature. It could be used in the future for connecting with models of HDPR or Marta in Vortex Studio too. Or many other different applications.

Anyway, it is true that right now drivers/udp is only used for ExoTeR. So if you think it should stay here, no problem from my side.

**Review by levingerdes — CHANGES_REQUESTED** [review]
It's really a useful and generic feature, you're right. But since no other rover uses this, I agree with Tim and would only include it in ExoTeR's package set.

We try to use the rover package set as the intersection of all our rovers' required packages. So as long as the vortex package is only present in the ExoTeR package set, udp should also only be in the same package set.

**Comment by gonzalopd96** [comment]
Done! drivers/udp re-included.

**Review by wieset — APPROVED** [review]

**Comment by wieset** [comment]
Thanks Gonzalo, looks good! I just tested the branch and it builds fine. Will merge it now.

**Comment by gonzalopd96** [comment]
Nice! Thanks Tim!

**Pull request merged**
