### PR TITLE
Add mission_control and unreal repos

### PR DESCRIPTION
**Pull request by gonzalopd96**
This new repos are used for the simulations with Unreal Engine and for the upcoming tests with ExoTeR at Málaga.

### CODE REVIEW

**Review by levingerdes — CHANGES_REQUESTED** [review]
The additions here are looking good and things are updating and compiling fine when switching the branch and only compiling the delta.

Before merging this, I'd like to ask you to fill in the ROCK `manifest.xml` files in the new packages. Those tell the build system which dependencies your packages have so that the build order can be adjusted. For example, I can see that `mission control` uses `udp`, `motion planning`, and `coupled control` among others (https://github.com/esa-prl/control-mission_control/blob/master/src/mission_control.hpp). Please add those here https://github.com/esa-prl/control-mission_control/blob/master/manifest.xml . In addition, you may want to see if you can't include the udp headers as it's done here: https://github.com/esa-prl/simulation-orogen-unreal/blob/master/tasks/Task.hpp

Please update `manifest.xml` in 
- [x] control/mission_control
- [ ] control/orogen/mission_control
- [ ] simulation/orogen/unreal

Check out this page https://www.rock-robotics.org/documentation/autoproj/advanced/package_dependencies.html or let me know if you need help.

Once this is done, I'd be happy to merge.

**Comment by levingerdes** [comment]
FYI, you can also add `Related to https://github.com/esa-prl/exoter-package_set/pull/2` to the bottom of your commit messages in other repositories to let the commits appear in this PR discussion.

**Comment by LMManto** [comment]
All the manifests have been updated. Just one question: what do you mean with "In addition, you may want to see if you can't include the udp headers as it's done here: https://github.com/esa-prl/simulation-orogen-unreal/blob/master/tasks/Task.hpp"? Thank you

**Review by levingerdes — APPROVED** [review]

**Comment by levingerdes** [comment]
That's perfect, I'll merge it in!

My comment about the udp `include` is not important for this merge but it might be interesting that you can try to use
`#include <udp/udp.hpp>` instead of the more cumbersome `#include "../../../drivers/udp/src/udp.hpp"` for example.

**Pull request merged**
